#!/bin/bash
set -x
HOSTNAME=
FQDN=
OS=
CFG=`dirname $0`/config.cfg
[ -r $CFG ] && . $CFG
read -p "Enter hostname? ($HOSTNAME): " hostname
[ -z "$hostname" ] && hostname=$HOSTNAME
read -p "Enter FQDN? ($FQDN): " fqdn
[ -z "$fqdn" ] && fqdn=$FQDN
read -p "Enter OS? ($OS): " os
[ -z "$os" ] && os=$OS
echo "# Config file autogenerated by `id -nu` on `date`" > $CFG
echo "# Do not edit by hand, this file will be rewritten" >> $CFG
echo >>$CFG
echo HOSTNAME=$hostname >> $CFG
echo FQDN=$fqdn >> $CFG
echo OS=$os >> $CFG
